---
- name: Redémarrer Apache sur Ubuntu
  service:
    name: "{{ apache_service_ubuntu }}"
    state: restarted
  when: ansible_os_family == "Debian"

- name: Redémarrer Apache sur Rocky Linux
  command: httpd -k restart
  when: ansible_os_family == "RedHat"
