---
drupal_version: "9.5.11"
drupal_download_url: "https://ftp.drupal.org/files/projects/drupal-{{ drupal_version }}.tar.gz"
drupal_install_dir: /var/www/html/drupal

drupal_db_name: drupal
drupal_db_user: drupal
drupal_db_password: drupal123
drupal_db_host: localhost
