---
php_packages_ubuntu:
  - php
  - php-mysql
  - php-xml
  - php-gd
  - php-curl
  - php-mbstring
  - php-zip

php_packages_rocky:
  - php
  - php-mysqlnd
  - php-xml
  - php-gd
  - php-curl
  - php-mbstring
  - php-zip
